# Generated by Django 3.1.7 on 2021-09-11 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_catergory',
            field=models.CharField(choices=[('Mindfulness and Stress Managment', 'Mindfulness and Stress Managment'), ('Physical Health', 'Physical Health'), ('Nutrition', 'Nutrition')], default='Mindfulness and Stress Managment', max_length=40),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(default='something', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
