# Generated by Django 3.2.7 on 2021-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
