# Generated by Django 3.1.7 on 2021-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApplication', '0002_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_catergory',
            field=models.CharField(choices=[('MSM', 'Mindfulness and Stress Managment'), ('PH', 'Physical Health'), ('N', 'Nutrition')], default='Choose one', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
