# Generated by Django 3.2.7 on 2021-09-11 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApplication', '0002_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_catergory',
            field=models.CharField(choices=[('MSM', 'Mindfulness and Stress Managment'), ('PH', 'Physical Health'), ('N', 'Nutrition')], default='MSM', max_length=40),
        ),
        migrations.AddField(
            model_name='activity',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
