# Generated by Django 3.1.7 on 2021-09-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApplication', '0002_auto_20210911_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='personID',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
