# Generated by Django 3.2.7 on 2021-09-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApplication', '0003_auto_20210911_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
