# Generated by Django 3.1.7 on 2021-09-11 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApplication', '0003_auto_20210911_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
