# Generated by Django 3.1.7 on 2021-09-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApplication', '0004_auto_20210911_1300'),
        ('WellnessApplication', '0004_alter_activity_activity_catergory'),
    ]

    operations = [
    ]
