# Generated by Django 3.1.7 on 2021-09-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApplication', '0005_merge_20210911_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_catergory',
            field=models.CharField(choices=[('Mindfulness and Stress Managment', 'Mindfulness and Stress Managment'), ('Physical Health', 'Physical Health'), ('Nutrition', 'Nutrition')], default='Mindfulness and Stress Managment', max_length=40),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
