# Generated by Django 3.2.7 on 2021-09-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellnessApplication', '0002_auto_20210911_1437'),
        ('WellnessApplication', '0004_alter_activity_id'),
        ('WellnessApplication', '0006_auto_20210911_1431'),
    ]

    operations = [
    ]
